matches:

  # https://github.com/dysfunc/ascii-emoji

  - trigger: ":shrug"
    replace: "Â¯\\_(ãƒ„)_/Â¯"
  - trigger: ":angryemo"
    replace: "à² _à² "
  - trigger: ":trollemo"
    replace: "( Í¡Â° ÍœÊ– Í¡Â°)"
  - trigger: ":tableflipemo"
    replace: "(â•¯Â°â–¡Â°ï¼‰â•¯ï¸µ â”»â”â”»"
  - trigger: ":scaredshrugemo"
    replace: "Â¯\\_(âŠ™ï¸¿âŠ™)_/Â¯"
  - trigger: ":exhaspemo"
    replace: "t(-_-t)"
  - trigger: ":loveeyesemo"
    replace: "â™¥â€¿â™¥"
  - trigger: ":blowkissemo"
    replace: "( Ë˜ Â³Ë˜)â™¥ "
  - trigger: ":singemo"
    replace: "ãƒ¾(Â´ã€‡`)ï¾‰â™ªâ™ªâ™ª"
  - trigger: ":happybearemo"
    replace: "(áµ”á´¥áµ”)"
  - trigger: ":pointemo"
    replace: "(â˜ï¾Ÿãƒ®ï¾Ÿ)â˜"
  - trigger: ":ashamedemo"
    replace: "(._.)"
  - trigger: ":sunglassesemo"
    replace: |
      ( â€¢_â€¢)
      ( â€¢_â€¢)>âŒâ– -â– 
      (âŒâ– _â– )

  - trigger: ":boxico"
    replace: "â–¡"
  - trigger: ":tickico"
    replace: "âœ“"
  - trigger: ":starico"
    replace: "â˜†"
  - trigger: ":crossico"
    replace: "âŒ"
  - trigger: ":tickinboxico"
    replace: "âœ…"
  - trigger: ":crossinboxico"
    replace: "â˜’"
  - trigger: ":heartico"
    replace: "â™¥"
  - trigger: ":handpointico"
    replace: "â˜"
  - trigger: ":arrowico"
    replace: "â†’"
  
  - trigger: ":grinning face:"
    replace: "ğŸ˜€"
  
  - trigger: ":grinning face with sweat:"
    replace: "ğŸ˜…"
  
  - trigger: ":face with tears of joy:"
    replace: "ğŸ˜‚"
  
  - trigger: ":thinking face:"
    replace: "ğŸ¤”"
    
  - trigger: ":rolling on the floor laughing:"
    replace: "ğŸ¤£"
    
  - trigger: ":tired face:"
    replace: "ğŸ˜«"